version: '3.1'

services:

  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
    expose:
      - '5432'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres

volumes:
  postgres_data:
